import { Card } from '../modelos/card';

export const CARDS: Card[] = [
    {
        titulo: 'Mi historia de Salud',
        subtitulo: 'Tus consultas almédico',
        icono: 'historial',
        botones: ['opcion-1', 'opcion2'],
        type: 'default',
        fecha: '27/01/21',
        path: 'miHuds',
        outlet: 'listado',
    },
    {
        titulo: 'Mis Laboratorios',
        subtitulo: 'Último registro',
        icono: 'recipiente',
        botones: ['opcion-1', 'opcion-2'],
        type: 'success',
        fecha: '27/09/20',
        path: 'misLaboratorios',
        outlet: 'listado',
    },
    {
        titulo: 'Mis Turnos',
        subtitulo: 'Último registro',
        icono: 'turno-bold',
        botones: ['opcion-1', 'opcion-2'],
        type: 'info',
        fecha: '23/11/20',
        path: 'misTurnos',
        outlet: 'listado',
    },
    {
        titulo: 'Mis Vacunas',
        subtitulo: 'Último registro',
        icono: 'vacuna',
        botones: ['opcion-1', 'opcion-2'],
        type: 'danger',
        fecha: '12/01/21',
        path: 'misVacunas',
        outlet: 'listado',
    },
    {
        titulo: 'Mis Familiares',
        subtitulo: 'Último registro',
        icono: 'familia',
        botones: ['opcion-1', 'opcion-2'],
        type: 'warning',
        fecha: '17/11/20',
        path: 'misFamiliares',
        outlet: 'listado',
    },
]
