import { Card } from '../modelos/card';

export const CARDS: Card[] = [

    {
        id: 0,
        titulo: 'inicio',
        subtitulo: '',
        tipo: '',
        semanticTag: '',
        icono: 'paciente-casa',
        path: 'miInicio',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 1,
        titulo: 'mi cuenta',
        subtitulo: 'datos personales',
        tipo: '',
        semanticTag: '',
        icono: 'paciente',
        path: 'misDatos',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 2,
        titulo: 'mis turnos',
        subtitulo: 'próximos, historial y obtención',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'turno-bold',
        path: 'misTurnos',
        color: '#00a8e0',
        outlet: 'listado',
    },
    {
        id: 3,
        titulo: 'mis vacunas',
        subtitulo: 'historial de vacunación',
        tipo: 'custom',
        semanticTag: 'procedimiento',
        icono: 'vacuna',
        path: 'misVacunas',
        color: '#aa1daa',
        outlet: 'listado',
    },
    {
        id: 4,
        titulo: 'mis laboratorios',
        subtitulo: 'descarga de resultados',
        tipo: 'custom',
        semanticTag: 'laboratorio',
        icono: 'recipiente',
        path: 'misLaboratorios',
        color: '#a0a0a0',
        outlet: 'listado',
    },
    {
        id: 5,
        titulo: 'mis certificados',
        subtitulo: 'descarga de informes',
        tipo: 'info',
        semanticTag: 'registro',
        icono: 'documento-cursor',
        path: 'misDocumentos',
        color: '#8bc43f',
        outlet: 'listado',
    },
    {
        id: 6,
        titulo: 'mis relaciones',
        subtitulo: 'permisos y cuentas delegadas',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'familia',
        path: 'misRelaciones',
        color: '#027a8a',
        outlet: 'listado',
    },
    // {
    //     id: 7,
    //     titulo: 'huds',
    //     subtitulo: '',
    //     tipo: 'info',
    //     semanticTag: 'solicitud',
    //     icono: 'historial',
    //     path: 'miHuds',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
    // {
    //     id: 8,
    //     titulo: 'consultas',
    //     subtitulo: '',
    //     tipo: 'custom',
    //     semanticTag: 'solicitud',
    //     icono: 'mano-corazon',
    //     path: 'misConsultas',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
    // {
    //     id: 9,
    //     titulo: 'problemas',
    //     subtitulo: '',
    //     tipo: 'custom',
    //     semanticTag: 'trastorno',
    //     icono: 'trastorno',
    //     path: 'misProblemas',
    //     color: '#ff4a1a',
    //     outlet: 'listado',
    // },
    // {
    //     id: 10,
    //     titulo: 'observaciones',
    //     subtitulo: '',
    //     tipo: 'custom',
    //     semanticTag: 'hallazgo',
    //     icono: 'lupa-ojo',
    //     path: 'misHallazgos',
    //     color: '#f4a03b',
    //     outlet: 'listado',
    // },
    // {
    //     id: 11,
    //     titulo: 'prácticas',
    //     subtitulo: '',
    //     tipo: 'custom',
    //     semanticTag: 'procedimiento',
    //     icono: 'termometro',
    //     path: 'misProcedimientos',
    //     color: '#92278e',
    //     outlet: 'listado',
    // },
    // {
    //     id: 12,
    //     titulo: 'prescripciones',
    //     subtitulo: '',
    //     tipo: 'custom',
    //     semanticTag: 'producto',
    //     icono: 'pildoras',
    //     path: 'misPrescripciones',
    //     color: '#00bcb4',
    //     outlet: 'listado',
    // },
    // {
    //     id: 13,
    //     titulo: 'mensajes',
    //     subtitulo: '',
    //     tipo: 'info',
    //     semanticTag: 'otro',
    //     icono: 'mail',
    //     path: 'misensajes',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
    // {
    //     id: 14,
    //     titulo: 'organizaciones',
    //     subtitulo: '',
    //     tipo: 'info',
    //     semanticTag: 'solicitud',
    //     icono: 'hospital',
    //     path: 'misOrganizaciones',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
    // {
    //     id: 15,
    //     titulo: 'equipo de salud',
    //     subtitulo: '',
    //     tipo: 'info',
    //     semanticTag: 'solicitud',
    //     icono: 'medico',
    //     path: 'miEquipo',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
    // {
    //     id: 16,
    //     titulo: 'derivaciones',
    //     subtitulo: '',
    //     tipo: 'info',
    //     semanticTag: 'solicitud',
    //     icono: 'avion',
    //     path: 'misSolicitudes',
    //     color: '#0070cc',
    //     outlet: 'listado',
    // },
];
