import { Card } from '../modelos/card';

export const CARDS: Card[] = [
    {
        id: 0,
        nombre: 'su cuenta',
        tipo: '',
        semanticTag: 'Pedro Ernesto Martinez',
        icono: 'paciente',
        path: '',
        color: '#941b80',
        outlet: '',
    },
    {
        id: 1,
        nombre: 'inicio',
        tipo: 'info',
        semanticTag: '',
        icono: 'paciente-casa',
        path: 'miInicio',
        color: '#00a8e0',
        outlet: '',
    },
    {
        id: 2,
        nombre: 'mis informes',
        tipo: 'info',
        semanticTag: 'registro',
        icono: 'documento-cursor',
        path: 'misDocumentos',
        color: '#0070cc',
        outlet: 'true',
    },
    {
        id: 3,
        nombre: 'mis turnos',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'turno-bold',
        path: 'misTurnos',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 4,
        nombre: 'mis mensajes',
        tipo: 'info',
        semanticTag: 'otro',
        icono: 'mail',
        path: 'misMensajes',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 5,
        nombre: 'mis medicamentos',
        tipo: 'custom',
        semanticTag: 'producto',
        icono: 'pildoras',
        path: 'misPrescripciones',
        color: '#00bcb4',
        outlet: '',
    },
    {
        id: 6,
        nombre: 'mis laboratorios',
        tipo: 'custom',
        semanticTag: 'laboratorio',
        icono: 'recipiente',
        path: 'misLaboratorios',
        color: '#a0a0a0',
        outlet: 'true',
    },
    {
        id: 7,
        nombre: 'mis vacunas',
        tipo: 'custom',
        semanticTag: 'procedimiento',
        icono: 'vacuna',
        path: 'misVacunas',
        color: '#92278e',
        outlet: 'true',
    },
    {
        id: 8,
        nombre: 'mis relaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'familia',
        path: 'misFamiliares',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 9,
        nombre: 'su huds',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'historial',
        path: 'miHuds',
        color: '#8cc63f',
        outlet: '',
    },
    {
        id: 10,
        nombre: 'mis consultas',
        tipo: 'custom',
        semanticTag: 'solicitud',
        icono: 'mano-corazon',
        path: 'misConsultas',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 11,
        nombre: 'su lista de problemas',
        tipo: 'custom',
        semanticTag: 'trastorno',
        icono: 'trastorno',
        path: 'misProblemas',
        color: '#ff4a1a',
        outlet: '',
    },
    {
        id: 12,
        nombre: 'mis informes',
        tipo: 'custom',
        semanticTag: 'hallazgo',
        icono: 'lupa-ojo',
        path: 'misProblemas',
        color: '#f4a03b',
        outlet: '',
    },
    {
        id: 13,
        nombre: 'mis prácticas',
        tipo: 'custom',
        semanticTag: 'procedimiento',
        icono: 'termometro',
        path: 'misLaboratorios',
        color: '#92278e',
        outlet: '',
    },
    {
        id: 14,
        nombre: 'mis organizaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'hospital',
        path: 'misOrganizaciones',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 15,
        nombre: 'su equipo de salud',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'medico',
        path: 'miEquipo',
        color: '#0070cc',
        outlet: '',
    },
    {
        id: 16,
        nombre: 'mis derivaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'avion',
        path: 'misSolicitudes',
        color: '#0070cc',
        outlet: '',
    },
]
